### ISSUE TITLE
Handling of special characters

### ISSUE THREAD

**Issue by rubensworks** [mmlab/owlturtle2http#3]
Apparently, this new version doesn't support special characters properly.
For example: 

```
...Range Fragments whose interval overlap with the Range Gateâ€™s interval.
```

should be

```
...Range Fragments whose interval overlap with the Range Gate's interval.
```

HTML: http://semweb.datasciencelab.be/ns/multidimensional-interface
OWL: https://git.datasciencelab.ugent.be/rtaelman/vocabulary-multidimensional-interface/blob/master/multidimensional-interface.owl

**Comment by tdn** [comment]
For now, I just changed your ’ in the owl file to '. Looks fine now.
Could it be the problem was that the former is not an UTF-8 character?

**Comment by DieterDePaepe** [comment]
I thought UTF-8 could represent any unicode character?

**Comment by RubenVerborgh** [comment]
This is a classical example of something being encoded in UTF-8 but being read in ASCII. I recognize the resulting mojibake. The read should state UTF-8 encoding explicitly.

@DieterDePaepe Not everything, otherwise UTF-16 wouldn't exist :wink:

**Comment by RubenVerborgh** [comment]
(Untested, but it has to be this.)

**Comment by DieterDePaepe** [comment]
@RubenVerborgh UTF-8 is variable encoding where minimal bytes is 1, UTF-16 is variable encoding where minimal bytes is 2. Both can encode unicode as a whole. That's at least how I remember it, and Wikipedia seems to back that up: "UTF-8 is a character encoding capable of encoding all possible characters, or code points, defined by Unicode and originally designed by Ken Thompson and Rob Pike."

**Comment by RubenVerborgh** [comment]
@ DieterDePaepe My source was likely wring then, thx!
