### ISSUE TITLE
Assets can not be found anymore

### ISSUE THREAD

**Issue by rubensworks** [mmlab/owlturtle2http#4]
It looks like 3d02ce555b1c128eb99773ea252c92717f9a590c broke asset locations, as can be seen here: http://semweb.datasciencelab.be/ns/multidimensional-interface/

If I'm correct, this tool generates the assets folder next to the ontology folder, and since the ontology folder contains the desired index file, the path should first go to the parent folder before going to the assets.
So I think this commit should be reverted (except for the copyright statement probably ;-) ).

**Comment by tdn** [comment]
Huh. Weird. It was the other way around for me before. Maybe the cache of my browser was acting up.
I'll fix it when I have 2 minutes ;-)
